// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoYj_R6EnW_DecvJSgN0a2pN5TgbYVY0',
    appId: '1:797677126570:web:640ccddf012fa78d30a1d3',
    messagingSenderId: '797677126570',
    projectId: 'portfolio-v1-5e59d',
    authDomain: 'portfolio-v1-5e59d.firebaseapp.com',
    storageBucket: 'portfolio-v1-5e59d.firebasestorage.app',
    measurementId: 'G-EY6798NRC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZK392WZVzmpA_swPuFq06U9ZUPyIC4Q',
    appId: '1:797677126570:android:38a8a478e3f460ee30a1d3',
    messagingSenderId: '797677126570',
    projectId: 'portfolio-v1-5e59d',
    storageBucket: 'portfolio-v1-5e59d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWgMxOY7A-AfM-9d1BtV83nTEZaCbvW4',
    appId: '1:797677126570:ios:4e573c72f38b02b330a1d3',
    messagingSenderId: '797677126570',
    projectId: 'portfolio-v1-5e59d',
    storageBucket: 'portfolio-v1-5e59d.firebasestorage.app',
    iosBundleId: 'com.example.portpolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWgMxOY7A-AfM-9d1BtV83nTEZaCbvW4',
    appId: '1:797677126570:ios:4e573c72f38b02b330a1d3',
    messagingSenderId: '797677126570',
    projectId: 'portfolio-v1-5e59d',
    storageBucket: 'portfolio-v1-5e59d.firebasestorage.app',
    iosBundleId: 'com.example.portpolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoYj_R6EnW_DecvJSgN0a2pN5TgbYVY0',
    appId: '1:797677126570:web:4132d48e4ad24ae030a1d3',
    messagingSenderId: '797677126570',
    projectId: 'portfolio-v1-5e59d',
    authDomain: 'portfolio-v1-5e59d.firebaseapp.com',
    storageBucket: 'portfolio-v1-5e59d.firebasestorage.app',
    measurementId: 'G-3NK20LXVM7',
  );

}